version: '3.8'

services:
  server:
    build: server/
    ports:
      - "8001:80"
    volumes:
      - ./server:/var/www/html
    #restart: always
    container_name: php-apache
  db:
    build: db/
    ports:
        - "3308:3308"
    container_name: db
    #restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
