version: '3.8'

services:
  server:
    build: servers/
    ports:
      - "8005:80"
    volumes:
      - ./servers:/var/www/html
    #restart: always
    container_name: php-apache-new
  db:
    image: mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
        - "3309:3309"
    container_name: db-new
    #restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
